### ISSUE TITLE
📌 Potential to-do lists after 06/22

### ISSUE THREAD

**Issue by andatoshiki** [andatoshiki/toshiki-proxypool#24]
# TODO

> This files contains the current to-do list for future and also some memos in case I forget, will be synced into issue#24 every time I update this file. **Note that this has not been fully formatted but with simple markdown listings (since all these were just a rush through of my memory on what I did/bugs/failures I encounter in a short time period in case I forget)**

self-hosted workflows issues and errors explained:

- [ ] Docker image build and deploy with ghcr.io registries, add personal access token according to https://github.com/skills/publish-packages documentation
- [ ] Difference between self make build and GitHub action auto build and release, how it works out.
- [ ] Go-Bindata command bash not found, make command incompatibility
- [ ] Only bind html or bind geoip database+html
- [ ] go report card cli, also usage of command go fmt for linting and formatting go source codes, refer to https://stackoverflow.com/questions/47735678/goland-how-to-use-gofmt
- [ ] dockerfile compilation errors behind it, not using the original forked "proxypool" default repository name in dockerfile but change to GitHub repository name in dockerfile in regard to ghcr.io
- [ ] Explain what the fuck is ghcr.io
- [ ] Failures on github dependabot package updating due to careless git-lfs tracking on all files ended with extension .go
- [ ] How to add a fucking GitHub personal access token as a repository secret in a repo for workflow to properly run
- [ ] Bindata command line .sh shell script completion
- [ ] GitHub default git push default is 25mb, but when it encounters files larger than 25mb, use either git lfs or increase the post buffer size with git config --global http.postBuffer 524288000 command, refer more at https://www.codegrepper.com/code-examples/shell/git+increase+buffer+size
- [ ] (Optional): CodeQl code security checking via workflows on GitHub for both javascript and golang
- [ ] Update packages manually, refer to this article on medium https://khorlee.medium.com/dependency-management-in-go-lang-using-go-commands-7900a7b2f760
- [ ] running make command on win based systems either via mingw32 or chocolatey, never tested on the other ones.
- [ ] Add heroku deployment option via app.json+heroku deploy button on README
- [ ] Add fly.io deployment option via fy.toml, refer to https://github.com/ssrlive/proxypool for newly implemented options.
- [ ] cloudflare/cache.go commented some lines due to not enough arguments, refer more at https://github.com/andatoshiki/toshiki-proxypool/runs/6932178272?check_suite_focus=true, solution found in https://github.com/ssrlive/proxypool
- [ ] golang.org/x/net and other pkgs require go version <=1.17.x, incompatible with greater versioned workflow runners, that causes error on building outputs, refer the issue here https://github.com/andatoshiki/toshiki-proxypool/runs/6930875206?check_suite_focus=true
- [ ] add bt/aapanel panel installation guide for Chinese users
- [ ] Building from source
- [ ] Go dev environment setup and running locally
- [x] Static html files and resources with Jsdelivrs CDN's might block the viewing speed of mainland Chinese user's page loading speed the fuck out, switch from cdn.jsdelivr... to fastly.jsdelivr...
- [ ] Explain the detailed reasons on why the first few workflows failed that was automatically triggered by dependabot, and view it's original workflow files for further debugging details
- [ ] Conventional commit via husky, not yet implemented, video on bilibili detailly explained
- [ ] PR templates, issue templates, discussions...
- [x] Changelog automatic generations by conventional commits
  - [x] Manually updated Changelog of `v0.0.1`
- [ ] Code of Conduct, contributing.md... in .github folder
- [ ] Documentations via docusaurus hosted in a subfolder of that doc site
- [ ] Reconstruct better looking READMEs
- [ ] Code owners, and it's original owners, full reasons on why this toshiki-proxypool project exists.
- [ ] Thanks to @xiaofei-ya's Note.md note file in the root folder of the repo, without that shit, my dev speed will be 10 times slower along with thousands of tabs on stackoverflow in my browser
- [ ] i18n language localizations and etc (Simplified Chinese, Traditional Chinese, English, Japanese), the program itself with Chinese commenting is fine, but the web UI
- [ ] Rewrite web UI, publish a new release without my own comments/links on, based on the original proxypool UI, rewrite using materialize framework (dark theme switch included)
- [ ] Also unifies the badge/shield styles based on shields.io, add extra shields
- [ ] Add repo star sparklines graphs in regard to https://github.com/antonmedv/spark
- [x] Redesign logo for proxypool
- [ ] Configure markdown, javascript, go... lint workflow action, currently unknown on how to work out
- [x] **Get some sleep you idiot**
- [ ] Rewrite the docs both in GitHub wikis, docsify and docusaurus for backup in case accessible domain blockages or CDN issues, **REMEMBER TO BACKUP THE IMAGES!**
- [ ] How to make the docker image/ghcr package public on GitHub
  - [ ] Linking to repo
  - [ ] Change visibility
  - [x] And a lot of other shits I don't know, but yes, sleep rn (update 6/17/2022)
- [x] FOSSA and codecov code analysis badge added
    - Add a coverage.txt file to the root of project for making codecov's API able to fetch the coverage report file.
- [x] Added country node speed white listing feature which is available to set through under config.yml
- [x] #37
- [ ] heroku alterbative-koyeb deployment
- [x] #41

**Comment by andatoshiki** [comment]
For new logos, please refer to [andatoshiki/toshiki-proxypool-ui](https://github.com/andatoshiki/toshiki-proxypool-ui), or with the following direct link with CDN from either UNPKG or JsDelivr for faster file serving.
- https://www.unpkg.com/@andatoshiki/toshiki-proxypool-ui@0.0.13/assets/img/toshiki-proxypool-logo@v0.0.13.png
- https://cdn.jsdelivr.net/gh/andatoshiki/toshiki-proxypool-ui@master/assets/img/toshiki-proxypool-logo%40v0.0.13.png

> Alternative with fastly CDN provider for JsDelivr if both of the link failed to response/load resources, https://fastly.jsdelivr.net/gh/andatoshiki/toshiki-proxypool-ui@master/assets/img/toshiki-proxypool-logo%40v0.0.13.png
